package com.example.test.bean;

public class Form {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form.stu_name
     *
     * @mbggenerated
     */
    private String stuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form.stu_num
     *
     * @mbggenerated
     */
    private String stuNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form.v_school
     *
     * @mbggenerated
     */
    private String vSchool;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form.v_college
     *
     * @mbggenerated
     */
    private String vCollege;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form.learn_type
     *
     * @mbggenerated
     */
    private String learnType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form.p_code
     *
     * @mbggenerated
     */
    private String pCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form.political_score
     *
     * @mbggenerated
     */
    private Integer politicalScore = 0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form.english_score
     *
     * @mbggenerated
     */
    private Integer englishScore = 0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form.p_one_score
     *
     * @mbggenerated
     */
    private Integer pOneScore = 0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form.p_two_score
     *
     * @mbggenerated
     */
    private Integer pTwoScore = 0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form.origin_school
     *
     * @mbggenerated
     */
    private String originSchool;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form.origin_profession
     *
     * @mbggenerated
     */
    private String originProfession;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form.prefer_city
     *
     * @mbggenerated
     */
    private String preferCity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form.id
     *
     * @return the value of form.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form.id
     *
     * @param id the value for form.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form.stu_name
     *
     * @return the value of form.stu_name
     *
     * @mbggenerated
     */
    public String getStuName() {
        return stuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form.stu_name
     *
     * @param stuName the value for form.stu_name
     *
     * @mbggenerated
     */
    public void setStuName(String stuName) {
        this.stuName = stuName == null ? null : stuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form.stu_num
     *
     * @return the value of form.stu_num
     *
     * @mbggenerated
     */
    public String getStuNum() {
        return stuNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form.stu_num
     *
     * @param stuNum the value for form.stu_num
     *
     * @mbggenerated
     */
    public void setStuNum(String stuNum) {
        this.stuNum = stuNum == null ? null : stuNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form.v_school
     *
     * @return the value of form.v_school
     *
     * @mbggenerated
     */
    public String getvSchool() {
        return vSchool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form.v_school
     *
     * @param vSchool the value for form.v_school
     *
     * @mbggenerated
     */
    public void setvSchool(String vSchool) {
        this.vSchool = vSchool == null ? null : vSchool.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form.v_college
     *
     * @return the value of form.v_college
     *
     * @mbggenerated
     */
    public String getvCollege() {
        return vCollege;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form.v_college
     *
     * @param vCollege the value for form.v_college
     *
     * @mbggenerated
     */
    public void setvCollege(String vCollege) {
        this.vCollege = vCollege == null ? null : vCollege.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form.learn_type
     *
     * @return the value of form.learn_type
     *
     * @mbggenerated
     */
    public String getLearnType() {
        return learnType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form.learn_type
     *
     * @param learnType the value for form.learn_type
     *
     * @mbggenerated
     */
    public void setLearnType(String learnType) {
        this.learnType = learnType == null ? null : learnType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form.p_code
     *
     * @return the value of form.p_code
     *
     * @mbggenerated
     */
    public String getpCode() {
        return pCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form.p_code
     *
     * @param pCode the value for form.p_code
     *
     * @mbggenerated
     */
    public void setpCode(String pCode) {
        this.pCode = pCode == null ? null : pCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form.political_score
     *
     * @return the value of form.political_score
     *
     * @mbggenerated
     */
    public Integer getPoliticalScore() {
        return politicalScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form.political_score
     *
     * @param politicalScore the value for form.political_score
     *
     * @mbggenerated
     */
    public void setPoliticalScore(Integer politicalScore) {
        this.politicalScore = politicalScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form.english_score
     *
     * @return the value of form.english_score
     *
     * @mbggenerated
     */
    public Integer getEnglishScore() {
        return englishScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form.english_score
     *
     * @param englishScore the value for form.english_score
     *
     * @mbggenerated
     */
    public void setEnglishScore(Integer englishScore) {
        this.englishScore = englishScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form.p_one_score
     *
     * @return the value of form.p_one_score
     *
     * @mbggenerated
     */
    public Integer getpOneScore() {
        return pOneScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form.p_one_score
     *
     * @param pOneScore the value for form.p_one_score
     *
     * @mbggenerated
     */
    public void setpOneScore(Integer pOneScore) {
        this.pOneScore = pOneScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form.p_two_score
     *
     * @return the value of form.p_two_score
     *
     * @mbggenerated
     */
    public Integer getpTwoScore() {
        return pTwoScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form.p_two_score
     *
     * @param pTwoScore the value for form.p_two_score
     *
     * @mbggenerated
     */
    public void setpTwoScore(Integer pTwoScore) {
        this.pTwoScore = pTwoScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form.origin_school
     *
     * @return the value of form.origin_school
     *
     * @mbggenerated
     */
    public String getOriginSchool() {
        return originSchool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form.origin_school
     *
     * @param originSchool the value for form.origin_school
     *
     * @mbggenerated
     */
    public void setOriginSchool(String originSchool) {
        this.originSchool = originSchool == null ? null : originSchool.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form.origin_profession
     *
     * @return the value of form.origin_profession
     *
     * @mbggenerated
     */
    public String getOriginProfession() {
        return originProfession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form.origin_profession
     *
     * @param originProfession the value for form.origin_profession
     *
     * @mbggenerated
     */
    public void setOriginProfession(String originProfession) {
        this.originProfession = originProfession == null ? null : originProfession.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form.prefer_city
     *
     * @return the value of form.prefer_city
     *
     * @mbggenerated
     */
    public String getPreferCity() {
        return preferCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form.prefer_city
     *
     * @param preferCity the value for form.prefer_city
     *
     * @mbggenerated
     */
    public void setPreferCity(String preferCity) {
        this.preferCity = preferCity == null ? null : preferCity.trim();
    }

    public Form(){

    }

    public Form(String[] strings){
        this.setStuName(strings[0]);
        this.setStuNum(strings[1]);
        this.setvSchool(strings[2]);
        this.setvCollege(strings[3]);
        this.setLearnType(strings[4]);
        this.setpCode(strings[5]);
        this.setPoliticalScore(Integer.valueOf(strings[6]));
        this.setEnglishScore(Integer.valueOf(strings[7]));
        this.setpOneScore(Integer.valueOf(strings[8]));
        this.setpTwoScore(Integer.valueOf(strings[9]));
        this.setOriginSchool(strings[10]);
        this.setOriginProfession(strings[11]);
        this.setPreferCity(strings[12]);
    }
}