package com.example.test.bean;

public class testInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_info.v_school
     *
     * @mbggenerated
     */
    private String vSchool;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_info.v_college
     *
     * @mbggenerated
     */
    private String vCollege;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_info.p_name
     *
     * @mbggenerated
     */
    private String pName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_info.p_code
     *
     * @mbggenerated
     */
    private String pCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_info.exam_contans
     *
     * @mbggenerated
     */
    private String examContans;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_info.sum
     *
     * @mbggenerated
     */
    private Integer sum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_info.line_one
     *
     * @mbggenerated
     */
    private Integer lineOne;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_info.line_two
     *
     * @mbggenerated
     */
    private Integer lineTwo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_info.school_type
     *
     * @mbggenerated
     */
    private String schoolType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_info.learn_type
     *
     * @mbggenerated
     */
    private String learnType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_info.p_level
     *
     * @mbggenerated
     */
    private String pLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_info.location
     *
     * @mbggenerated
     */
    private String location;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_info.id
     *
     * @return the value of test_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_info.id
     *
     * @param id the value for test_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_info.v_school
     *
     * @return the value of test_info.v_school
     *
     * @mbggenerated
     */
    public String getvSchool() {
        return vSchool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_info.v_school
     *
     * @param vSchool the value for test_info.v_school
     *
     * @mbggenerated
     */
    public void setvSchool(String vSchool) {
        this.vSchool = vSchool == null ? null : vSchool.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_info.v_college
     *
     * @return the value of test_info.v_college
     *
     * @mbggenerated
     */
    public String getvCollege() {
        return vCollege;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_info.v_college
     *
     * @param vCollege the value for test_info.v_college
     *
     * @mbggenerated
     */
    public void setvCollege(String vCollege) {
        this.vCollege = vCollege == null ? null : vCollege.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_info.p_name
     *
     * @return the value of test_info.p_name
     *
     * @mbggenerated
     */
    public String getpName() {
        return pName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_info.p_name
     *
     * @param pName the value for test_info.p_name
     *
     * @mbggenerated
     */
    public void setpName(String pName) {
        this.pName = pName == null ? null : pName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_info.p_code
     *
     * @return the value of test_info.p_code
     *
     * @mbggenerated
     */
    public String getpCode() {
        return pCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_info.p_code
     *
     * @param pCode the value for test_info.p_code
     *
     * @mbggenerated
     */
    public void setpCode(String pCode) {
        this.pCode = pCode == null ? null : pCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_info.exam_contans
     *
     * @return the value of test_info.exam_contans
     *
     * @mbggenerated
     */
    public String getExamContans() {
        return examContans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_info.exam_contans
     *
     * @param examContans the value for test_info.exam_contans
     *
     * @mbggenerated
     */
    public void setExamContans(String examContans) {
        this.examContans = examContans == null ? null : examContans.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_info.sum
     *
     * @return the value of test_info.sum
     *
     * @mbggenerated
     */
    public Integer getSum() {
        return sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_info.sum
     *
     * @param sum the value for test_info.sum
     *
     * @mbggenerated
     */
    public void setSum(Integer sum) {
        this.sum = sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_info.line_one
     *
     * @return the value of test_info.line_one
     *
     * @mbggenerated
     */
    public Integer getLineOne() {
        return lineOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_info.line_one
     *
     * @param lineOne the value for test_info.line_one
     *
     * @mbggenerated
     */
    public void setLineOne(Integer lineOne) {
        this.lineOne = lineOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_info.line_two
     *
     * @return the value of test_info.line_two
     *
     * @mbggenerated
     */
    public Integer getLineTwo() {
        return lineTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_info.line_two
     *
     * @param lineTwo the value for test_info.line_two
     *
     * @mbggenerated
     */
    public void setLineTwo(Integer lineTwo) {
        this.lineTwo = lineTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_info.school_type
     *
     * @return the value of test_info.school_type
     *
     * @mbggenerated
     */
    public String getSchoolType() {
        return schoolType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_info.school_type
     *
     * @param schoolType the value for test_info.school_type
     *
     * @mbggenerated
     */
    public void setSchoolType(String schoolType) {
        this.schoolType = schoolType == null ? null : schoolType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_info.learn_type
     *
     * @return the value of test_info.learn_type
     *
     * @mbggenerated
     */
    public String getLearnType() {
        return learnType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_info.learn_type
     *
     * @param learnType the value for test_info.learn_type
     *
     * @mbggenerated
     */
    public void setLearnType(String learnType) {
        this.learnType = learnType == null ? null : learnType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_info.p_level
     *
     * @return the value of test_info.p_level
     *
     * @mbggenerated
     */
    public String getpLevel() {
        return pLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_info.p_level
     *
     * @param pLevel the value for test_info.p_level
     *
     * @mbggenerated
     */
    public void setpLevel(String pLevel) {
        this.pLevel = pLevel == null ? null : pLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_info.location
     *
     * @return the value of test_info.location
     *
     * @mbggenerated
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_info.location
     *
     * @param location the value for test_info.location
     *
     * @mbggenerated
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }
}