package com.example.test.mapper;

import com.example.test.bean.testInfo;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface testInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_info
     *
     * @mbggenerated
     */
    int insert(testInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_info
     *
     * @mbggenerated
     */
    int insertSelective(testInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_info
     *
     * @mbggenerated
     */
    testInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(testInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(testInfo record);

    List<testInfo> selectBySchoolAndPCode(String vSchool, String pCode);


}